version: "3"

services:
  jekyll:
      image: jekyll/jekyll:3.8.6
      command: jekyll serve --watch --force_polling --drafts
      ports:
        - 4000:4000
      volumes:
        - .:/srv/jekyll
